-- ============================================================================
-- 174_processing_template_suite_v2.sql
-- ----------------------------------------------------------------------------
-- UI-simplification lane: upgrade the four ACTIVE default templates to the v2
-- simplified suite. v2 removes the six retired display fields (Farm, Planned
-- Processing Date (SF), Actual/Planned Time On Farm, Time Remaining Until
-- Processing, Product Pick-up Date) and makes Customer a SINGLE select sourced
-- from settings.customer_options (like Processor). Broiler carries 11 fields;
-- cattle/pig/sheep carry 10.
--
-- Contract (Codex-gated):
--   * FAIL CLOSED: a program upgrades ONLY when its active template's fields
--     are byte-for-byte (jsonb-equal) the known default v1 that mig 172 seeded.
--     Anything else — an administrator customized it — RAISES and (under
--     psql --single-transaction) rolls the whole migration back.
--   * IDEMPOTENT: an active template already carrying the v2 fields is a no-op.
--   * CHECKLIST PRESERVED: the new v2 version carries the ACTIVE template's
--     checklist VERBATIM (admin re-pointing of step assignees survives). Only
--     when a program has no active template at all (fresh environment with the
--     seed removed) is the canonical default checklist used.
--   * NEVER deletes template rows or touches processing_records — stored field
--     values (including values of retired fields) are kept.
--
-- The v2 JSON below is the CANONICAL suite from src/lib/processingFields.js
-- defaultProcessingTemplateSuite(); the static guard
-- processing_template_suite_static.test.js asserts equality both ways
-- (174 v2 == JS suite; 174 expected-v1 == 172 seed) so nothing can drift.
-- created_by reuses the importer actor helper (first admin) — service/psql
-- applies have no auth.uid(). Error class: PROCESSING_VALIDATION:.
-- NO BEGIN/COMMIT (TEST via exec_sql; PROD via psql --single-transaction).
-- Depends on: 156 (templates table), 162 (customer_options), 164
-- (_processing_import_actor), 172 (v1 seed).
-- ============================================================================

DO $mig$
DECLARE
  v_program   text;
  v_v1        jsonb;
  v_v2        jsonb;
  v_checklist jsonb;
  v_expected  int;
  v_active    public.processing_templates;
BEGIN
  FOREACH v_program IN ARRAY ARRAY['broiler','cattle','pig','sheep'] LOOP
    v_v1 :=
      CASE v_program WHEN 'broiler' THEN '[{"id":"procActual","name":"Actual Processing Date (SF)","type":"date"},{"id":"status","name":"Status (Processing)","type":"single","options":[{"key":"planned","label":"Planned","color":{"bg":"#E8B73E","ink":"#5A4304"}},{"key":"reserved","label":"Reserved","color":{"bg":"#93C896","ink":"#285F33"}},{"key":"in_proccess","label":"In-Proccess","color":{"bg":"#E4924A","ink":"#6F3711"}},{"key":"completed","label":"Completed","color":{"bg":"#E07A6E","ink":"#6E1C15"}},{"key":"tbc","label":"TBC","color":{"bg":"#E59CC0","ink":"#6F2A50"}},{"key":"goal","label":"Goal","color":{"bg":"#6AA6DD","ink":"#173B5E"}}]},{"id":"program","name":"Farm Programs","type":"single","options":[{"key":"broiler","label":"Broiler","color":{"bg":"#E8B73E","ink":"#5A4304"}},{"key":"cattle","label":"Cattle","color":{"bg":"#F0B3A8","ink":"#9F3322"}},{"key":"pig","label":"Pigs","color":{"bg":"#6AA6DD","ink":"#173B5E"}},{"key":"sheep","label":"Lambs","color":{"bg":"#93C896","ink":"#285F33"}}]},{"id":"batchName","name":"Batch Name (Farms)","type":"text"},{"id":"farm","name":"Farm","type":"single","options":[{"key":"wcf","label":"WCF","color":{"bg":"#DDF1EE","ink":"#2E7A73"}}]},{"id":"animals","name":"Animals Processed","type":"number"},{"id":"condemned","name":"Condemed","type":"number"},{"id":"farmArrival","name":"Farm Arrival Date","type":"date"},{"id":"year","name":"Year","type":"single","options":[{"key":"y2026","label":"2026","color":{"bg":"#EDEFF1","ink":"#5B626C"}},{"key":"y2027","label":"2027","color":{"bg":"#EDEFF1","ink":"#5B626C"}}]},{"id":"animalMaster","name":"Status (Animal Master)","type":"single","options":[{"key":"scheduled","label":"Scheduled","color":{"bg":"#EDEFF1","ink":"#5B626C"}},{"key":"on_farm","label":"On Farm","color":{"bg":"#E7EDF8","ink":"#3B6CB7"}},{"key":"inventoried","label":"Inventoried","color":{"bg":"#DDF1EE","ink":"#2E7A73"}}]},{"id":"procPlanned","name":"Planned Processing Date (SF)","type":"date"},{"id":"actualTOF","name":"Actual Time On Farm","type":"formula"},{"id":"plannedTOF","name":"Planned Time on Farm","type":"formula"},{"id":"timeRemaining","name":"Time Remaining Until Processing","type":"formula"},{"id":"productPickup","name":"Product Pick-up Date","type":"date"},{"id":"customer","name":"Customer (Broiler)","type":"multi","options":[{"key":"sonnys","label":"Sonny''s","color":{"bg":"#BFE3CB","ink":"#245737"}},{"key":"coastal_confirmed","label":"Coastal Pastures - CONFIRMED","color":{"bg":"#F0B3A8","ink":"#9F3322"}},{"key":"coastal_potential","label":"Coastal Pastures - POTENTIAL","color":{"bg":"#EFC07E","ink":"#875213"}}]},{"id":"processor","name":"Processor","type":"single","optionsSource":"settings.processor_options"}]'::jsonb
           WHEN 'cattle' THEN '[{"id":"procActual","name":"Actual Processing Date (SF)","type":"date"},{"id":"status","name":"Status (Processing)","type":"single","options":[{"key":"planned","label":"Planned","color":{"bg":"#E8B73E","ink":"#5A4304"}},{"key":"reserved","label":"Reserved","color":{"bg":"#93C896","ink":"#285F33"}},{"key":"in_proccess","label":"In-Proccess","color":{"bg":"#E4924A","ink":"#6F3711"}},{"key":"completed","label":"Completed","color":{"bg":"#E07A6E","ink":"#6E1C15"}},{"key":"tbc","label":"TBC","color":{"bg":"#E59CC0","ink":"#6F2A50"}},{"key":"goal","label":"Goal","color":{"bg":"#6AA6DD","ink":"#173B5E"}}]},{"id":"program","name":"Farm Programs","type":"single","options":[{"key":"broiler","label":"Broiler","color":{"bg":"#E8B73E","ink":"#5A4304"}},{"key":"cattle","label":"Cattle","color":{"bg":"#F0B3A8","ink":"#9F3322"}},{"key":"pig","label":"Pigs","color":{"bg":"#6AA6DD","ink":"#173B5E"}},{"key":"sheep","label":"Lambs","color":{"bg":"#93C896","ink":"#285F33"}}]},{"id":"batchName","name":"Batch Name (Farms)","type":"text"},{"id":"farm","name":"Farm","type":"single","options":[{"key":"wcf","label":"WCF","color":{"bg":"#DDF1EE","ink":"#2E7A73"}}]},{"id":"animals","name":"Animals Processed","type":"number"},{"id":"condemned","name":"Condemed","type":"number"},{"id":"farmArrival","name":"Farm Arrival Date","type":"date"},{"id":"year","name":"Year","type":"single","options":[{"key":"y2026","label":"2026","color":{"bg":"#EDEFF1","ink":"#5B626C"}},{"key":"y2027","label":"2027","color":{"bg":"#EDEFF1","ink":"#5B626C"}}]},{"id":"animalMaster","name":"Status (Animal Master)","type":"single","options":[{"key":"scheduled","label":"Scheduled","color":{"bg":"#EDEFF1","ink":"#5B626C"}},{"key":"on_farm","label":"On Farm","color":{"bg":"#E7EDF8","ink":"#3B6CB7"}},{"key":"inventoried","label":"Inventoried","color":{"bg":"#DDF1EE","ink":"#2E7A73"}}]},{"id":"procPlanned","name":"Planned Processing Date (SF)","type":"date"},{"id":"actualTOF","name":"Actual Time On Farm","type":"formula"},{"id":"plannedTOF","name":"Planned Time on Farm","type":"formula"},{"id":"timeRemaining","name":"Time Remaining Until Processing","type":"formula"},{"id":"productPickup","name":"Product Pick-up Date","type":"date"},{"id":"processor","name":"Processor","type":"single","optionsSource":"settings.processor_options"}]'::jsonb
           WHEN 'pig' THEN '[{"id":"procActual","name":"Actual Processing Date (SF)","type":"date"},{"id":"status","name":"Status (Processing)","type":"single","options":[{"key":"planned","label":"Planned","color":{"bg":"#E8B73E","ink":"#5A4304"}},{"key":"reserved","label":"Reserved","color":{"bg":"#93C896","ink":"#285F33"}},{"key":"in_proccess","label":"In-Proccess","color":{"bg":"#E4924A","ink":"#6F3711"}},{"key":"completed","label":"Completed","color":{"bg":"#E07A6E","ink":"#6E1C15"}},{"key":"tbc","label":"TBC","color":{"bg":"#E59CC0","ink":"#6F2A50"}},{"key":"goal","label":"Goal","color":{"bg":"#6AA6DD","ink":"#173B5E"}}]},{"id":"program","name":"Farm Programs","type":"single","options":[{"key":"broiler","label":"Broiler","color":{"bg":"#E8B73E","ink":"#5A4304"}},{"key":"cattle","label":"Cattle","color":{"bg":"#F0B3A8","ink":"#9F3322"}},{"key":"pig","label":"Pigs","color":{"bg":"#6AA6DD","ink":"#173B5E"}},{"key":"sheep","label":"Lambs","color":{"bg":"#93C896","ink":"#285F33"}}]},{"id":"batchName","name":"Batch Name (Farms)","type":"text"},{"id":"farm","name":"Farm","type":"single","options":[{"key":"wcf","label":"WCF","color":{"bg":"#DDF1EE","ink":"#2E7A73"}}]},{"id":"animals","name":"Animals Processed","type":"number"},{"id":"condemned","name":"Condemed","type":"number"},{"id":"farmArrival","name":"Farm Arrival Date","type":"date"},{"id":"year","name":"Year","type":"single","options":[{"key":"y2026","label":"2026","color":{"bg":"#EDEFF1","ink":"#5B626C"}},{"key":"y2027","label":"2027","color":{"bg":"#EDEFF1","ink":"#5B626C"}}]},{"id":"animalMaster","name":"Status (Animal Master)","type":"single","options":[{"key":"scheduled","label":"Scheduled","color":{"bg":"#EDEFF1","ink":"#5B626C"}},{"key":"on_farm","label":"On Farm","color":{"bg":"#E7EDF8","ink":"#3B6CB7"}},{"key":"inventoried","label":"Inventoried","color":{"bg":"#DDF1EE","ink":"#2E7A73"}}]},{"id":"procPlanned","name":"Planned Processing Date (SF)","type":"date"},{"id":"actualTOF","name":"Actual Time On Farm","type":"formula"},{"id":"plannedTOF","name":"Planned Time on Farm","type":"formula"},{"id":"timeRemaining","name":"Time Remaining Until Processing","type":"formula"},{"id":"productPickup","name":"Product Pick-up Date","type":"date"},{"id":"processor","name":"Processor","type":"single","optionsSource":"settings.processor_options"}]'::jsonb
           WHEN 'sheep' THEN '[{"id":"procActual","name":"Actual Processing Date (SF)","type":"date"},{"id":"status","name":"Status (Processing)","type":"single","options":[{"key":"planned","label":"Planned","color":{"bg":"#E8B73E","ink":"#5A4304"}},{"key":"reserved","label":"Reserved","color":{"bg":"#93C896","ink":"#285F33"}},{"key":"in_proccess","label":"In-Proccess","color":{"bg":"#E4924A","ink":"#6F3711"}},{"key":"completed","label":"Completed","color":{"bg":"#E07A6E","ink":"#6E1C15"}},{"key":"tbc","label":"TBC","color":{"bg":"#E59CC0","ink":"#6F2A50"}},{"key":"goal","label":"Goal","color":{"bg":"#6AA6DD","ink":"#173B5E"}}]},{"id":"program","name":"Farm Programs","type":"single","options":[{"key":"broiler","label":"Broiler","color":{"bg":"#E8B73E","ink":"#5A4304"}},{"key":"cattle","label":"Cattle","color":{"bg":"#F0B3A8","ink":"#9F3322"}},{"key":"pig","label":"Pigs","color":{"bg":"#6AA6DD","ink":"#173B5E"}},{"key":"sheep","label":"Lambs","color":{"bg":"#93C896","ink":"#285F33"}}]},{"id":"batchName","name":"Batch Name (Farms)","type":"text"},{"id":"farm","name":"Farm","type":"single","options":[{"key":"wcf","label":"WCF","color":{"bg":"#DDF1EE","ink":"#2E7A73"}}]},{"id":"animals","name":"Animals Processed","type":"number"},{"id":"condemned","name":"Condemed","type":"number"},{"id":"farmArrival","name":"Farm Arrival Date","type":"date"},{"id":"year","name":"Year","type":"single","options":[{"key":"y2026","label":"2026","color":{"bg":"#EDEFF1","ink":"#5B626C"}},{"key":"y2027","label":"2027","color":{"bg":"#EDEFF1","ink":"#5B626C"}}]},{"id":"animalMaster","name":"Status (Animal Master)","type":"single","options":[{"key":"scheduled","label":"Scheduled","color":{"bg":"#EDEFF1","ink":"#5B626C"}},{"key":"on_farm","label":"On Farm","color":{"bg":"#E7EDF8","ink":"#3B6CB7"}},{"key":"inventoried","label":"Inventoried","color":{"bg":"#DDF1EE","ink":"#2E7A73"}}]},{"id":"procPlanned","name":"Planned Processing Date (SF)","type":"date"},{"id":"actualTOF","name":"Actual Time On Farm","type":"formula"},{"id":"plannedTOF","name":"Planned Time on Farm","type":"formula"},{"id":"timeRemaining","name":"Time Remaining Until Processing","type":"formula"},{"id":"productPickup","name":"Product Pick-up Date","type":"date"},{"id":"processor","name":"Processor","type":"single","optionsSource":"settings.processor_options"}]'::jsonb
      END;
    v_v2 :=
      CASE v_program WHEN 'broiler' THEN '[{"id":"procActual","name":"Actual Processing Date (SF)","type":"date"},{"id":"status","name":"Status (Processing)","type":"single","options":[{"key":"planned","label":"Planned","color":{"bg":"#E8B73E","ink":"#5A4304"}},{"key":"reserved","label":"Reserved","color":{"bg":"#93C896","ink":"#285F33"}},{"key":"in_proccess","label":"In-Proccess","color":{"bg":"#E4924A","ink":"#6F3711"}},{"key":"completed","label":"Completed","color":{"bg":"#E07A6E","ink":"#6E1C15"}},{"key":"tbc","label":"TBC","color":{"bg":"#E59CC0","ink":"#6F2A50"}},{"key":"goal","label":"Goal","color":{"bg":"#6AA6DD","ink":"#173B5E"}}]},{"id":"program","name":"Farm Programs","type":"single","options":[{"key":"broiler","label":"Broiler","color":{"bg":"#E8B73E","ink":"#5A4304"}},{"key":"cattle","label":"Cattle","color":{"bg":"#F0B3A8","ink":"#9F3322"}},{"key":"pig","label":"Pigs","color":{"bg":"#6AA6DD","ink":"#173B5E"}},{"key":"sheep","label":"Lambs","color":{"bg":"#93C896","ink":"#285F33"}}]},{"id":"batchName","name":"Batch Name (Farms)","type":"text"},{"id":"animals","name":"Animals Processed","type":"number"},{"id":"condemned","name":"Condemed","type":"number"},{"id":"farmArrival","name":"Farm Arrival Date","type":"date"},{"id":"year","name":"Year","type":"single","options":[{"key":"y2026","label":"2026","color":{"bg":"#EDEFF1","ink":"#5B626C"}},{"key":"y2027","label":"2027","color":{"bg":"#EDEFF1","ink":"#5B626C"}}]},{"id":"animalMaster","name":"Status (Animal Master)","type":"single","options":[{"key":"scheduled","label":"Scheduled","color":{"bg":"#EDEFF1","ink":"#5B626C"}},{"key":"on_farm","label":"On Farm","color":{"bg":"#E7EDF8","ink":"#3B6CB7"}},{"key":"inventoried","label":"Inventoried","color":{"bg":"#DDF1EE","ink":"#2E7A73"}}]},{"id":"customer","name":"Customer (Broiler)","type":"single","optionsSource":"settings.customer_options"},{"id":"processor","name":"Processor","type":"single","optionsSource":"settings.processor_options"}]'::jsonb
           WHEN 'cattle' THEN '[{"id":"procActual","name":"Actual Processing Date (SF)","type":"date"},{"id":"status","name":"Status (Processing)","type":"single","options":[{"key":"planned","label":"Planned","color":{"bg":"#E8B73E","ink":"#5A4304"}},{"key":"reserved","label":"Reserved","color":{"bg":"#93C896","ink":"#285F33"}},{"key":"in_proccess","label":"In-Proccess","color":{"bg":"#E4924A","ink":"#6F3711"}},{"key":"completed","label":"Completed","color":{"bg":"#E07A6E","ink":"#6E1C15"}},{"key":"tbc","label":"TBC","color":{"bg":"#E59CC0","ink":"#6F2A50"}},{"key":"goal","label":"Goal","color":{"bg":"#6AA6DD","ink":"#173B5E"}}]},{"id":"program","name":"Farm Programs","type":"single","options":[{"key":"broiler","label":"Broiler","color":{"bg":"#E8B73E","ink":"#5A4304"}},{"key":"cattle","label":"Cattle","color":{"bg":"#F0B3A8","ink":"#9F3322"}},{"key":"pig","label":"Pigs","color":{"bg":"#6AA6DD","ink":"#173B5E"}},{"key":"sheep","label":"Lambs","color":{"bg":"#93C896","ink":"#285F33"}}]},{"id":"batchName","name":"Batch Name (Farms)","type":"text"},{"id":"animals","name":"Animals Processed","type":"number"},{"id":"condemned","name":"Condemed","type":"number"},{"id":"farmArrival","name":"Farm Arrival Date","type":"date"},{"id":"year","name":"Year","type":"single","options":[{"key":"y2026","label":"2026","color":{"bg":"#EDEFF1","ink":"#5B626C"}},{"key":"y2027","label":"2027","color":{"bg":"#EDEFF1","ink":"#5B626C"}}]},{"id":"animalMaster","name":"Status (Animal Master)","type":"single","options":[{"key":"scheduled","label":"Scheduled","color":{"bg":"#EDEFF1","ink":"#5B626C"}},{"key":"on_farm","label":"On Farm","color":{"bg":"#E7EDF8","ink":"#3B6CB7"}},{"key":"inventoried","label":"Inventoried","color":{"bg":"#DDF1EE","ink":"#2E7A73"}}]},{"id":"processor","name":"Processor","type":"single","optionsSource":"settings.processor_options"}]'::jsonb
           WHEN 'pig' THEN '[{"id":"procActual","name":"Actual Processing Date (SF)","type":"date"},{"id":"status","name":"Status (Processing)","type":"single","options":[{"key":"planned","label":"Planned","color":{"bg":"#E8B73E","ink":"#5A4304"}},{"key":"reserved","label":"Reserved","color":{"bg":"#93C896","ink":"#285F33"}},{"key":"in_proccess","label":"In-Proccess","color":{"bg":"#E4924A","ink":"#6F3711"}},{"key":"completed","label":"Completed","color":{"bg":"#E07A6E","ink":"#6E1C15"}},{"key":"tbc","label":"TBC","color":{"bg":"#E59CC0","ink":"#6F2A50"}},{"key":"goal","label":"Goal","color":{"bg":"#6AA6DD","ink":"#173B5E"}}]},{"id":"program","name":"Farm Programs","type":"single","options":[{"key":"broiler","label":"Broiler","color":{"bg":"#E8B73E","ink":"#5A4304"}},{"key":"cattle","label":"Cattle","color":{"bg":"#F0B3A8","ink":"#9F3322"}},{"key":"pig","label":"Pigs","color":{"bg":"#6AA6DD","ink":"#173B5E"}},{"key":"sheep","label":"Lambs","color":{"bg":"#93C896","ink":"#285F33"}}]},{"id":"batchName","name":"Batch Name (Farms)","type":"text"},{"id":"animals","name":"Animals Processed","type":"number"},{"id":"condemned","name":"Condemed","type":"number"},{"id":"farmArrival","name":"Farm Arrival Date","type":"date"},{"id":"year","name":"Year","type":"single","options":[{"key":"y2026","label":"2026","color":{"bg":"#EDEFF1","ink":"#5B626C"}},{"key":"y2027","label":"2027","color":{"bg":"#EDEFF1","ink":"#5B626C"}}]},{"id":"animalMaster","name":"Status (Animal Master)","type":"single","options":[{"key":"scheduled","label":"Scheduled","color":{"bg":"#EDEFF1","ink":"#5B626C"}},{"key":"on_farm","label":"On Farm","color":{"bg":"#E7EDF8","ink":"#3B6CB7"}},{"key":"inventoried","label":"Inventoried","color":{"bg":"#DDF1EE","ink":"#2E7A73"}}]},{"id":"processor","name":"Processor","type":"single","optionsSource":"settings.processor_options"}]'::jsonb
           WHEN 'sheep' THEN '[{"id":"procActual","name":"Actual Processing Date (SF)","type":"date"},{"id":"status","name":"Status (Processing)","type":"single","options":[{"key":"planned","label":"Planned","color":{"bg":"#E8B73E","ink":"#5A4304"}},{"key":"reserved","label":"Reserved","color":{"bg":"#93C896","ink":"#285F33"}},{"key":"in_proccess","label":"In-Proccess","color":{"bg":"#E4924A","ink":"#6F3711"}},{"key":"completed","label":"Completed","color":{"bg":"#E07A6E","ink":"#6E1C15"}},{"key":"tbc","label":"TBC","color":{"bg":"#E59CC0","ink":"#6F2A50"}},{"key":"goal","label":"Goal","color":{"bg":"#6AA6DD","ink":"#173B5E"}}]},{"id":"program","name":"Farm Programs","type":"single","options":[{"key":"broiler","label":"Broiler","color":{"bg":"#E8B73E","ink":"#5A4304"}},{"key":"cattle","label":"Cattle","color":{"bg":"#F0B3A8","ink":"#9F3322"}},{"key":"pig","label":"Pigs","color":{"bg":"#6AA6DD","ink":"#173B5E"}},{"key":"sheep","label":"Lambs","color":{"bg":"#93C896","ink":"#285F33"}}]},{"id":"batchName","name":"Batch Name (Farms)","type":"text"},{"id":"animals","name":"Animals Processed","type":"number"},{"id":"condemned","name":"Condemed","type":"number"},{"id":"farmArrival","name":"Farm Arrival Date","type":"date"},{"id":"year","name":"Year","type":"single","options":[{"key":"y2026","label":"2026","color":{"bg":"#EDEFF1","ink":"#5B626C"}},{"key":"y2027","label":"2027","color":{"bg":"#EDEFF1","ink":"#5B626C"}}]},{"id":"animalMaster","name":"Status (Animal Master)","type":"single","options":[{"key":"scheduled","label":"Scheduled","color":{"bg":"#EDEFF1","ink":"#5B626C"}},{"key":"on_farm","label":"On Farm","color":{"bg":"#E7EDF8","ink":"#3B6CB7"}},{"key":"inventoried","label":"Inventoried","color":{"bg":"#DDF1EE","ink":"#2E7A73"}}]},{"id":"processor","name":"Processor","type":"single","optionsSource":"settings.processor_options"}]'::jsonb
      END;
    v_checklist :=
      CASE v_program WHEN 'broiler' THEN '[{"label":"Send Weight & Animal Count","assignee":"Ronnie Jones","assignee_profile_id":null},{"label":"Prepare Cut List","assignee":"Brian Naide","assignee_profile_id":null},{"label":"Add to Processing Spreadsheet by Protein","assignee":"Brett Post","assignee_profile_id":null},{"label":"Create Invoice from Farm to Customer","assignee":"Brett Post","assignee_profile_id":null},{"label":"Inventory in Product and add to Asana","assignee":"Brian Naide","assignee_profile_id":null},{"label":"If Applicable - Send photo of new product label","assignee":"Brian Naide","assignee_profile_id":null},{"label":"Add Inventory to Shopify","assignee":"Isabel Hermann","assignee_profile_id":null},{"label":"Reconcile and Analyze Podio","assignee":"Ronnie Jones","assignee_profile_id":null}]'::jsonb
           WHEN 'cattle' THEN '[{"label":"Send Weight & Animal Count","assignee":"Ronnie Jones","assignee_profile_id":null},{"label":"Prepare Cut List","assignee":"Ronnie Jones","assignee_profile_id":null},{"label":"Create and Post Inventory Intake Sheet","assignee":"Brett Post","assignee_profile_id":null},{"label":"Determine Wholesale Price / Animal","assignee":"Brett Post","assignee_profile_id":null},{"label":"Add to Processing Spreadsheet by Protein","assignee":"Brett Post","assignee_profile_id":null},{"label":"Create Invoice from Farm to Customer","assignee":"Brett Post","assignee_profile_id":null},{"label":"Obtain Product List from Processor & Send to Debbie","assignee":"Isabel Hermann","assignee_profile_id":null},{"label":"Inventory in Product & Send to Debbie","assignee":"Isabel Hermann","assignee_profile_id":null},{"label":"If Applicable - Send photo of new product label to Debbie","assignee":"Isabel Hermann","assignee_profile_id":null},{"label":"Add Inventory to Shopify","assignee":"Jessica Torres","assignee_profile_id":null},{"label":"Reconcile and Analyze Podio","assignee":"Ronnie Jones","assignee_profile_id":null},{"label":"Prepare Cutlist for Processor","assignee":"Ronnie Jones","assignee_profile_id":null},{"label":"Approve Cutlist","assignee":"Isabel Hermann","assignee_profile_id":null},{"label":"Inventory in Product through Asana Inventory Form","assignee":"Jessica Torres","assignee_profile_id":null},{"label":"Schedule/Notify payment of Kill & Processing","assignee":"Ronnie Jones","assignee_profile_id":null},{"label":"Update Status to Inventoried","assignee":"Jessica Torres","assignee_profile_id":null}]'::jsonb
           WHEN 'pig' THEN '[{"label":"Send Weight & Animal Count","assignee":"Ronnie Jones","assignee_profile_id":null},{"label":"Prepare Cut List","assignee":"Ronnie Jones","assignee_profile_id":null},{"label":"Add to Processing Spreadsheet by Protein","assignee":"Brett Post","assignee_profile_id":null},{"label":"Create Invoice from Farm to Customer","assignee":"Brett Post","assignee_profile_id":null},{"label":"Inventory in Product and add to Asana","assignee":"Isabel Hermann","assignee_profile_id":null},{"label":"If Applicable - Send photo of new product label","assignee":"Isabel Hermann","assignee_profile_id":null},{"label":"Add Inventory to Shopify","assignee":"Jessica Torres","assignee_profile_id":null},{"label":"Reconcile and Analyze Podio","assignee":"Ronnie Jones","assignee_profile_id":null},{"label":"Inventory in Product through Asana Inventory Form","assignee":"Jessica Torres","assignee_profile_id":null},{"label":"If Applicable - Send photo of new product label to Debbie","assignee":"Isabel Hermann","assignee_profile_id":null},{"label":"Update Status to Inventoried","assignee":"Jessica Torres","assignee_profile_id":null}]'::jsonb
           WHEN 'sheep' THEN '[{"label":"Send Weight & Animal Count","assignee":"Ronnie Jones","assignee_profile_id":null},{"label":"Prepare Cut List","assignee":"Ronnie Jones","assignee_profile_id":null},{"label":"Add to Processing Spreadsheet by Protein","assignee":"Brett Post","assignee_profile_id":null},{"label":"Create Invoice from Farm to Customer","assignee":"Brett Post","assignee_profile_id":null},{"label":"Inventory in Product and add to Asana","assignee":"Isabel Hermann","assignee_profile_id":null},{"label":"If Applicable - Send photo of new product label","assignee":"Isabel Hermann","assignee_profile_id":null},{"label":"Add Inventory to Shopify","assignee":"Jessica Torres","assignee_profile_id":null},{"label":"Reconcile and Analyze Podio","assignee":"Ronnie Jones","assignee_profile_id":null},{"label":"Update Final Animal Count & Weight","assignee":"Ronnie Jones","assignee_profile_id":null},{"label":"Schedule/Notify payment of Kill & Processing with Jennifer","assignee":"Ronnie Jones","assignee_profile_id":null},{"label":"Obtain Product List from Processor & Save to Egnyte","assignee":"Isabel Hermann","assignee_profile_id":null},{"label":"Inventory in Product through Asana Inventory Form","assignee":"Jessica Torres","assignee_profile_id":null},{"label":"If Applicable - Send photo of new product label to Debbie","assignee":"Isabel Hermann","assignee_profile_id":null},{"label":"Approve Cutlist","assignee":"Isabel Hermann","assignee_profile_id":null},{"label":"Prepare Cutlist for Processor","assignee":"Ronnie Jones","assignee_profile_id":null},{"label":"Update Status to Inventoried","assignee":"Jessica Torres","assignee_profile_id":null}]'::jsonb
      END;
    v_expected := CASE v_program WHEN 'broiler' THEN 11 ELSE 10 END;

    IF jsonb_array_length(v_v2) <> v_expected THEN
      RAISE EXCEPTION 'PROCESSING_VALIDATION: v2 % template must carry exactly % fields (found %)',
        v_program, v_expected, jsonb_array_length(v_v2);
    END IF;

    SELECT * INTO v_active
      FROM public.processing_templates
     WHERE program = v_program AND is_active = true;

    IF NOT FOUND THEN
      -- Fresh environment with no active template: seed v2 directly with the
      -- canonical default checklist.
      INSERT INTO public.processing_templates (id, program, version, fields, checklist, is_active, created_by)
      VALUES ('ptpl-default-' || v_program || '-v2', v_program,
              COALESCE((SELECT max(version) FROM public.processing_templates WHERE program = v_program), 0) + 1,
              v_v2, v_checklist, true, public._processing_import_actor());
      CONTINUE;
    END IF;

    IF v_active.fields = v_v2 THEN
      CONTINUE; -- already upgraded — reapplication is a no-op
    END IF;

    IF v_active.fields IS DISTINCT FROM v_v1 THEN
      RAISE EXCEPTION 'PROCESSING_VALIDATION: active % template (v%) was administrator-customized — refusing the automatic v2 upgrade; publish the change from the Templates manager instead',
        v_program, v_active.version;
    END IF;

    -- Known default v1 -> supersede with v2, preserving the checklist VERBATIM.
    UPDATE public.processing_templates SET is_active = false WHERE id = v_active.id;
    INSERT INTO public.processing_templates (id, program, version, fields, checklist, is_active, created_by)
    VALUES ('ptpl-default-' || v_program || '-v2', v_program, v_active.version + 1,
            v_v2, v_active.checklist, true, public._processing_import_actor());
  END LOOP;
END
$mig$;
